# Generated by Django 6.0.4 on 2026-05-02 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_estado", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_empresa", models.CharField(max_length=100)),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_finalizacion", models.DateField(blank=True, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "correo_electronico",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "responsable",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_empresas.estado",
                    ),
                ),
            ],
        ),
    ]
